# configure the pipeline to run based on different triggers
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#triggers
pool:
  vmImage: "ubuntu-18.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"

  - script: npm install
    displayName: "Install dependencies"

- task: replacetokens@3
  inputs:
    targetFiles: 'config.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTransforms: false
    enableTelemetry: true
    
  - script: npm run test
    displayName: "run tests"
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/Results*.xml'